### ISSUE TITLE
Add unit tests and linting

### ISSUE THREAD

**Issue by nfischer** [nfischer/n_shell#3]
It'd be nice to reuse some of the tests written for [n_](https://github.com/borisdiakur/n_), which uses the mocha framework and jshint.

If anyone is interested in taking up a PR for this (which would be awesome!), please ping this thread to give me a heads up. This is pretty low on my priority list, but if you'd like to see unit tests to improve project stability, please let me know.

**Comment by JessieFrance** [comment]
This is a really cool project! It's neat to see NodeJS work similar to Bash, and I like how this package even takes into account things like my home working directory.

For tests and linting, I noticed that n_ changed to using ESLint and AVA. Would you still want to use Mocha and JSHint? I think it would be fun to work on this issue regardless of linting/testing framework.

**Comment by nfischer** [comment]
eslint would be consistent with what we have in the ShellJS repo. Copying that config would be a good starting point. I'm fine with either ava or mocha.

**Comment by JessieFrance** [comment]
Using the ShellJS eslint configuration sounds great. Thank you!

**Comment by nfischer** [comment]
The bulk of this should be fixed now. Thanks again for your help!

**Comment by JessieFrance** [comment]
Thank you! It was a lot of fun. I love the new readme badges.
